package spk.local;
import java.io.*;
public final class CombatEngineM1Test{
 public static void main(String[]a)throws Exception{
  MovementState m=new MovementState();PetState ps=new PetState();DevAuthorityWorkbench dev=new DevAuthorityWorkbench();NpcRegistry npcs=new NpcRegistry(dev);ByteArrayOutputStream out=new ByteArrayOutputStream();ServerPacketWriter w=new ServerPacketWriter(out,new IsaacCipher(new int[]{1,2,3,4}));npcs.bootstrap(w,m,ps);
  NpcEntity pvp=npcs.scene(2);pvp.x=m.x()+1;pvp.y=m.y();EquipmentState eq=new EquipmentState();CombatEngine c=new CombatEngine(dev);
  String r=c.request(pvp,m,28526,System.currentTimeMillis());req(r.contains("PLAYER_PVP"),r);String h=c.tick(m,npcs,eq,w,10L);req(h!=null&&h.contains("damage=100")&&h.contains("damageAuthority=LOCAL_DEV_FIXTURE")&&h.contains("damageFormula=LOCAL_M2_FIXED_DUMMY_HIT")&&h.contains("damageMode=RULES_LOCAL_M2_FIXED_DUMMY_HIT")&&h.contains("attackAnim=15552")&&h.contains("speedTicks=3"),String.valueOf(h));req(c.consumeLastDamage()==100,"consume damage100");req(c.consumeLastDamage()==0,"consume clears");req(c.tick(m,npcs,eq,w,11L)==null,"tick11 early");req(c.tick(m,npcs,eq,w,12L)==null,"tick12 early");String h2=c.tick(m,npcs,eq,w,13L);req(h2!=null&&h2.contains("attackCount=2"),String.valueOf(h2));
  eq.setWeapon(28860);NpcEntity pvm=npcs.scene(3);pvm.x=m.x()+5;pvm.y=m.y();r=c.request(pvm,m,28860,System.currentTimeMillis());req(r.contains("NPC_PVM"),r);String sc=c.tick(m,npcs,eq,w,20L);req(sc!=null&&sc.contains("damage=200")&&sc.contains("damageAuthority=LOCAL_DEV_FIXTURE")&&sc.contains("damageFormula=LOCAL_M2_FIXED_DUMMY_HIT")&&sc.contains("damageMode=RULES_LOCAL_M2_FIXED_DUMMY_HIT")&&sc.contains("attackAnim=15409")&&sc.contains("profileAttackAnim=15624")&&sc.contains("animationAuthority=V9.13_DIRECT_RUNTIME")&&sc.contains("actorGfx=4080")&&sc.contains("actorGfxPublished=true")&&sc.contains("projectile=4079")&&sc.contains("speedTicks=3")&&sc.contains("hitsplatType=6"),String.valueOf(sc));req(c.consumeLastDamage()==200,"consume damage200");
  // Local dev workbench remains able to trial a specific animation explicitly; it never changes production authority.
  dev.setCombatAnimationOverride(28860,Integer.valueOf(15624));r=c.request(pvm,m,28860,System.currentTimeMillis());String trial=c.tick(m,npcs,eq,w,30L);req(trial!=null&&trial.contains("attackAnim=15624")&&trial.contains("animationAuthority=TEMPORARY_OVERRIDE"),String.valueOf(trial));
  System.out.println("V5141_COMBAT_M2_V913_PROMOTION_PASS bloodrend28526=anim15552_pvp100 scorching28860=anim15409_gfx4080_proj4079_speed3 obsolete15624NotNormal=true devTrialStillExplicit=true formulasDeferred=true");
 }
 static void req(boolean b,String s){if(!b)throw new AssertionError(s);}
}