package spk.local;
import java.io.*;import java.lang.reflect.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import java.util.concurrent.*;
public final class EngineR5ItemLibrarySocketTest{
 public static void main(String[]args)throws Exception{
  Path tmp=Files.createTempDirectory("spk-v5150-itemlib-");String old=System.getProperty("spk.local.accountFile");System.setProperty("spk.local.accountFile",tmp.resolve("opensrc.properties").toString());World world=World.isolatedForTest(80L);LocalMonsterSpawnerActivationRuntime monsterSpawner=LocalLabMonsterSpawnerProvisioning.create(world);InetAddress loop=InetAddress.getByName("127.0.0.1");
  try(ServerSocket ss=new ServerSocket(0,1,loop)){ExecutorService ex=Executors.newFixedThreadPool(2);Future<?> accept=ex.submit(()->{try{Socket s=ss.accept();new LocalSession(s,true,true,world,monsterSpawner).run();}catch(IOException e){throw new RuntimeException(e);}});Client c=null;try{
   c=login(loop,ss.getLocalPort(),"opensrc");waitFor(()->world.players().size()==1,3000,"login");waitFor(()->world.tickTargetsSnapshot().size()==1,3000,"session ready");drainUntilQuiet(c.s,1500,100);
   sendCommand(c,"monsterspawner");byte[] m=awaitPayload(c.s,3000,"Monster Spawner open","LocalLab placeholder 1 (NPC 1530)\n");has(m,"LocalLab placeholder 1 (NPC 1530)\n");
   sendWidget(c,MonsterSpawnerPresentation.rowWidget(0));byte[] selected=awaitPayload(c.s,3000,"Monster Spawner row selection","You have selected: @yel@LocalLab placeholder 1 (NPC 1530)\n");has(selected,"You have selected: @yel@LocalLab placeholder 1 (NPC 1530)\n");if(world.npcs().size()!=0)throw new AssertionError("row selection unexpectedly spawned NPC");
   sendCommand(c,"igsearch Scorching bow (i)");byte[] r=awaitPayload(c.s,3000,"item guide search","ITEM_GUIDE_RESET_PREVIEW\n","Scorching bow (i)\n","anim 15409");has(r,"ITEM_GUIDE_RESET_PREVIEW\n");has(r,"Scorching bow (i)\n");has(r,"anim 15409");
   sendWidget(c,MonsterSpawnerPresentation.TOGGLE_WIDGET);sendWidget(c,47816);byte[] b=awaitPayload(c.s,3000,"bonus widget after closed Monster Spawner toggle","ITEM_GUIDE_BONUS_WIDGET ON\n","N/A\n");has(b,"ITEM_GUIDE_BONUS_WIDGET ON\n");has(b,"N/A\n");if(world.npcs().size()!=0)throw new AssertionError("Item Library root 47500 left Monster Spawner gate open");
   sendCommand(c,"monsterspawner");byte[] reopened=awaitPayload(c.s,3000,"Monster Spawner reopen","You have selected: @yel@LocalLab placeholder 1 (NPC 1530)\n");has(reopened,"You have selected: @yel@LocalLab placeholder 1 (NPC 1530)\n");
   sendCommand(c,"igsearch definitely-not-an-item");sendWidget(c,MonsterSpawnerPresentation.TOGGLE_WIDGET);waitFor(()->world.npcs().size()==1,3000,"unknown igsearch preserved Monster Spawner gate");
   System.out.println("V5150_ENGINE_R5_ITEM_LIBRARY_SOCKET_PASS c2s103Igsearch=true nativeRootPopulation=true v913RuntimeDescription=true bonusButton185=true unknownProfilesNA=true monsterSpawnerGateRevokedByRoot47500=true unknownIgsearchPreservesGate=true");
  }finally{if(c!=null)c.close();waitFor(()->world.players().size()==0,3000,"logout");accept.get(3,TimeUnit.SECONDS);ex.shutdown();if(!ex.awaitTermination(3,TimeUnit.SECONDS))ex.shutdownNow();}}
  finally{world.close();if(old==null)System.clearProperty("spk.local.accountFile");else System.setProperty("spk.local.accountFile",old);try(java.util.stream.Stream<Path>st=Files.walk(tmp)){st.sorted(Comparator.reverseOrder()).forEach(p->{try{Files.deleteIfExists(p);}catch(Exception ignored){}});}}
 }
 static final class Client implements AutoCloseable{final Socket s;final IsaacCipher cipher;Client(Socket s,IsaacCipher c){this.s=s;this.cipher=c;}public void close()throws IOException{s.close();}}
 static Client login(InetAddress a,int port,String user)throws Exception{Socket s=new Socket(a,port);s.setSoTimeout(5000);InputStream in=s.getInputStream();OutputStream out=s.getOutputStream();out.write(14);out.write(7);out.flush();byte[] pre=Binary.readExactly(in,9);if((pre[8]&255)!=0)throw new AssertionError("prelogin");long seed=Binary.i64(Binary.readExactly(in,8),0);int[] seeds={0x01020304,0x11223344,(int)(seed>>>32),(int)seed};Method m=DualProfileSocketIntegrationTest.class.getDeclaredMethod("loginPayload",int[].class,String.class);m.setAccessible(true);byte[] payload=(byte[])m.invoke(null,seeds,user);out.write(16);out.write(payload.length);out.write(payload);out.flush();byte[] reply=Binary.readExactly(in,3);if((reply[0]&255)!=2)throw new AssertionError("login rc="+(reply[0]&255));IsaacCipher c=new IsaacCipher(seeds.clone());out.write((185+c.nextInt())&255);out.write(3);out.write(912);out.flush();return new Client(s,c);}
 static void sendCommand(Client c,String cmd)throws Exception{byte[] body=(cmd+"\n").getBytes(StandardCharsets.ISO_8859_1);OutputStream out=c.s.getOutputStream();out.write((103+c.cipher.nextInt())&255);out.write(body.length);out.write(body);out.flush();}
 static void sendWidget(Client c,int w)throws Exception{OutputStream out=c.s.getOutputStream();out.write((185+c.cipher.nextInt())&255);out.write((w>>>8)&255);out.write(w&255);out.flush();}
 static byte[] drain(Socket s,long total)throws Exception{InputStream in=s.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();long end=System.currentTimeMillis()+total;while(System.currentTimeMillis()<end){int n=in.available();if(n>0){byte[] b=new byte[Math.min(n,8192)];int r=in.read(b);if(r>0){o.write(b,0,r);end=Math.max(end,System.currentTimeMillis()+50);}}else Thread.sleep(5);}return o.toByteArray();}
 static byte[] drainUntilQuiet(Socket s,long timeout,long quietMillis)throws Exception{InputStream in=s.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();long end=System.currentTimeMillis()+timeout,quietUntil=System.currentTimeMillis()+quietMillis;while(System.currentTimeMillis()<end){int n=in.available();if(n>0){byte[] b=new byte[Math.min(n,8192)];int r=in.read(b);if(r>0){o.write(b,0,r);quietUntil=System.currentTimeMillis()+quietMillis;}}else{if(System.currentTimeMillis()>=quietUntil)return o.toByteArray();Thread.sleep(5);}}return o.toByteArray();}
 static byte[] awaitPayload(Socket s,long timeout,String label,String...needles)throws Exception{InputStream in=s.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();long end=System.currentTimeMillis()+timeout;while(System.currentTimeMillis()<end){int n=in.available();if(n>0){byte[] b=new byte[Math.min(n,8192)];int r=in.read(b);if(r>0){o.write(b,0,r);byte[] all=o.toByteArray();if(hasAll(all,needles))return all;}}else Thread.sleep(5);}byte[] all=o.toByteArray();throw new AssertionError(label+" timeout bytes="+all.length+" missing="+missing(all,needles));}
 static boolean hasAll(byte[] b,String...xs){for(String x:xs)if(!contains(b,x))return false;return true;}
 static String missing(byte[] b,String...xs){ArrayList<String> m=new ArrayList<>();for(String x:xs)if(!contains(b,x))m.add(x.replace("\n","\\n"));return m.toString();}
 static boolean contains(byte[]b,String x){byte[]n=x.getBytes(StandardCharsets.ISO_8859_1);outer:for(int i=0;i+n.length<=b.length;i++){for(int j=0;j<n.length;j++)if(b[i+j]!=n[j])continue outer;return true;}return false;}
 static void has(byte[]b,String x){if(!contains(b,x))throw new AssertionError("missing "+x+" bytes="+b.length);}
 interface Check{boolean ok();}static void waitFor(Check c,long ms,String label)throws Exception{long e=System.currentTimeMillis()+ms;while(System.currentTimeMillis()<e){if(c.ok())return;Thread.sleep(10);}throw new AssertionError(label+" timeout");}
}
