package spk.local;

public final class EngineR82FullResearchArchiveTest {
 public static void main(String[]args)throws Exception{
  if(FullResearchArchiveAuthority.sourceHashes().size()!=10)throw new AssertionError("source hash pins");
  if(FullResearchArchiveAuthority.datasetCount()!=67||FullResearchArchiveAuthority.rowLevelDatasetCount()!=62)throw new AssertionError("manifest "+FullResearchArchiveAuthority.summary());
  if(PetProcResearchAuthority.count()!=23||PetProcResearchAuthority.componentCount()!=47||PetProcResearchAuthority.animationTimingCount()!=101||PetProcResearchAuthority.gfxTimingCount()!=55||PetProcResearchAuthority.variantFamilyCount()!=32||PetProcResearchAuthority.specialRendererCount()!=9||PetProcResearchAuthority.remainingRuntimeCount()!=14)throw new AssertionError("item/pet R4 "+PetProcResearchAuthority.corpusSummary());
  if(EquipmentResearchAuthority.relationshipCount()!=33||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/equipment_static_mechanics_r82.tsv")!=729||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/equipment_current_i_bin_stat_r82.tsv")!=181||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/equipment_current_equippable_stat_r82.tsv")!=99||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/equipment_core_bonus_r82.tsv")!=284||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/equipment_speed_damage_r82.tsv")!=51||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/equipment_conditional_r82.tsv")!=565||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/equipment_pet_modifiers_r82.tsv")!=160)throw new AssertionError("equipment R2");
  if(WorldFullResearchAuthority.EFFECTIVE_UNIQUE_REGIONS!=1279||WorldFullResearchAuthority.FINAL_REGION_ROWS!=1283||WorldFullResearchAuthority.STATIC_PLACEMENTS!=2162982||WorldFullResearchAuthority.COLLIDABLE_PLACEMENTS!=1316740||WorldFullResearchAuthority.ADJACENCY_ROWS!=2002||WorldFullResearchAuthority.COMPONENTS!=72||WorldFullResearchAuthority.UNRESOLVED_GAPS!=54||WorldFullResearchAuthority.NAMED_CUSTOM_REGIONS!=68||WorldFullResearchAuthority.CUSTOM_GROUPS!=46)throw new AssertionError("WORLD R1");
  if(AssetRuntimeResearchAuthority.CONFIGURED_MAYA!=107||AssetRuntimeResearchAuthority.UNIQUE_KEYFRAMES!=105||AssetRuntimeResearchAuthority.SKELETON_FAMILIES!=28||AssetRuntimeResearchAuthority.BOUND_MODELS!=39||AssetRuntimeResearchAuthority.EXACT_SKELETON_REUSE_ADDITIONAL!=184||AssetRuntimeResearchAuthority.OBJECT_MODEL_PAIRS_ATTEMPTED!=17506||AssetRuntimeResearchAuthority.OBJECT_MODEL_PARSED!=17505||AssetRuntimeResearchAuthority.RIG_EQUIVALENCE_FAMILIES!=644||AssetRuntimeResearchAuthority.CURRENT_PLACED_CANDIDATE_ROWS!=37||AssetRuntimeResearchAuthority.CURRENT_PLACED_CANDIDATE_REFS!=676||AssetRuntimeResearchAuthority.MISSING_MODEL_ROWS!=44||AssetRuntimeResearchAuthority.MISSING_MODEL_REFS!=742)throw new AssertionError("asset R8");
  if(FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/r30_weapon_presentation_resolver_r82.tsv")!=496||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/r30_wield_presentation_resolver_r82.tsv")!=1501||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/r30_spell_presentation_r82.tsv")!=126||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/r30_prayer_presentation_r82.tsv")!=51||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/r30_ammo_presentation_r82.tsv")!=605||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/r30_special_presentation_r82.tsv")!=107||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/r30_upstream_animation_remap_r82.tsv")!=637||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/r30_upstream_gfx_remap_r82.tsv")!=186||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/r30_item_clone_graph_r82.tsv")!=2899||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/r30_model_identity_edges_r82.tsv")!=21477||FullResearchArchiveAuthority.countRows("/spk/local/data/research_r82/r30_v911_runtime_anchors_r82.tsv")!=34)throw new AssertionError("presentation R30");
  if(ServiceResearchAuthority.RECOVERY_MATRIX_ROWS!=20||ServiceResearchAuthority.ROUTER_ROWS!=16||ServiceResearchAuthority.SERVICE_KEY_ROWS!=9||ServiceResearchAuthority.PRODUCTION_OBJECT_EXAMPLES!=7)throw new AssertionError("NPC/WORLD/SHOP R1");
  if(PetMovementResearchAuthority.samples()!=5002||PetMovementResearchAuthority.movementEvents()!=10317||PetMovementResearchAuthority.reanchorCandidates()!=9||!"PLAYER_TO_MAIN_PET_TO_MINI_PET".equals(PetMovementResearchAuthority.get("relationship_authority")))throw new AssertionError("V9.12 movement "+PetMovementResearchAuthority.summary());
  System.out.println("V5182_ENGINE_R82_FULL_RESEARCH_ARCHIVE_PASS sources=10 datasets=67 rowLevel=62 itemPetR4=23/47/101/55/32/9 equipmentR2=729 worldR1=1279/2162982/1316740 assetR8=105/28/644 presentationR30=496/1501/126/51/605/107 movementSamples=5002 serviceR1=20/16/9/7");
 }
}
