package spk.local;
import java.io.*;import java.lang.reflect.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import java.util.concurrent.*;

public final class EngineR7DevPanelSocketTest {
 public static void main(String[]args)throws Exception{
  Path tmp=Files.createTempDirectory("spk-v5170-devpanel-");String old=System.getProperty("spk.local.accountFile");System.setProperty("spk.local.accountFile",tmp.resolve("opensrc.properties").toString());World world=World.isolatedForTest(80L);InetAddress loop=InetAddress.getByName("127.0.0.1");
  try(ServerSocket ss=new ServerSocket(0,1,loop)){ExecutorService ex=Executors.newFixedThreadPool(2);Future<?> accept=ex.submit(()->{try{Socket s=ss.accept();new LocalSession(s,true,true,world).run();}catch(IOException e){throw new RuntimeException(e);}});Client c=null;try{
   c=login(loop,ss.getLocalPort(),"opensrc");waitFor(()->world.players().size()==1,3000,"login");Thread.sleep(500);drain(c.s,300);
   sendCommand(c,"devpanel");byte[] main=drainUntil(c.s,3000,"LocalLab Dev Control Center | v5.18.5\n");has(main,"LocalLab Dev Control Center | v5.18.5\n");has(main,"Combat & weapons\n");has(main,"Pets\n");has(main,"Magic & prayer\n");has(main,"More systems...\n");
   sendWidget(c,2482);byte[] combat=drainUntil(c.s,2500,"Combat | ");has(combat,"Combat | ");has(combat,"Attack animation...\n");has(combat,"Hitsplat lab...\n");
   sendWidget(c,2482);byte[] anim=drainUntil(c.s,2500,"Attack animation | weapon ");has(anim,"Attack animation | weapon ");has(anim,"Set animation ID...\n");
   sendWidget(c,2482);byte[] prompt=drain(c.s,700);
   sendAmount(c,777);byte[] applied=drainUntil(c.s,2500,"Reset to authority\n");has(applied,"| 777\n");has(applied,"Reset to authority\n");
   sendWidget(c,2485);byte[] back=drainUntil(c.s,2500,"Combat | ");has(back,"Combat | ");
   sendCommand(c,"devpanel");drain(c.s,800);sendWidget(c,2485);byte[] more=drainUntil(c.s,2500,"More systems\n");has(more,"More systems\n");has(more,"World & collision\n");has(more,"Items & native UI\n");has(more,"Player / NPC lab\n");has(more,"Diagnostics\n");
   sendCommand(c,"devpanel");drain(c.s,800);sendWidget(c,2484);byte[] mp=drainUntil(c.s,2500,"Magic / Prayer | spells=126 prayers=51\n");has(mp,"Magic / Prayer | spells=126 prayers=51\n");has(mp,"Magic controls...\n");has(mp,"Prayer controls...\n");
   sendWidget(c,2482);byte[] magic=drainUntil(c.s,2500,"Magic book | ");has(magic,"Magic book | ");has(magic,"Modern\n");has(magic,"Ancient\n");has(magic,"Lunar\n");
   sendWidget(c,2485);drain(c.s,700);sendWidget(c,2483);byte[] prayer=drainUntil(c.s,2500,"Prayer | ");has(prayer,"Prayer | ");has(prayer,"Toggle prayer book\n");has(prayer,"Toggle widget ID...\n");has(prayer,"Manual head icon...\n");
   sendCommand(c,"devpanel");drain(c.s,700);sendWidget(c,2485);drain(c.s,700);sendWidget(c,2485);byte[] diag=drainUntil(c.s,2500,"Diagnostics | ");has(diag,"Diagnostics | ");has(diag,"Authority browser...\n");
   sendWidget(c,2483);byte[] auth=drainUntil(c.s,2500,"Authority browser | read-only | PASS");has(auth,"Authority browser | read-only | PASS");has(auth,"Magic / prayer authority...\n");has(auth,"World / item authority...\n");has(auth,"Research closure...\n");
   sendWidget(c,2484);byte[] research=drainUntil(c.s,2500,"Research closure | ");has(research,"Research closure | ");has(research,"Client discovery...\n");
   sendWidget(c,2485);byte[] discovery=drainUntil(c.s,2500,"Client discovery | ");has(discovery,"Client discovery | ");has(discovery,"Asset/model closure...\n");
   sendWidget(c,2485);byte[] asset=drainUntil(c.s,2500,"Asset/model closure | ");has(asset,"Asset/model closure | ");has(asset,"Client/assets alignment...\n");
   sendWidget(c,2482);byte[] align=drainUntil(c.s,2500,"Client/assets alignment | PASS");has(align,"Client/assets alignment | PASS");has(align,"Show pinned hashes\n");has(align,"Authority census\n");has(align,"Root 328 reconciliation\n");
   System.out.println("V5182_ENGINE_R82_DEV_PANEL_SOCKET_PASS native2480=true mouseWidget185=true keyboardSharedRoute=true nativeAmount27_208=true runtimeAnimationOverride=true categories=combat/pets/magic/prayer/world/items/player-npc/diagnostics magicBooks=3 prayerWidgetSelector=true sessionLocal=true");
  }finally{if(c!=null)c.close();waitFor(()->world.players().size()==0,3000,"logout");accept.get(3,TimeUnit.SECONDS);ex.shutdown();if(!ex.awaitTermination(3,TimeUnit.SECONDS))ex.shutdownNow();}}
  finally{world.close();if(old==null)System.clearProperty("spk.local.accountFile");else System.setProperty("spk.local.accountFile",old);try(java.util.stream.Stream<Path>st=Files.walk(tmp)){st.sorted(Comparator.reverseOrder()).forEach(p->{try{Files.deleteIfExists(p);}catch(Exception ignored){}});}}
 }
 static final class Client implements AutoCloseable{final Socket s;final IsaacCipher cipher;Client(Socket s,IsaacCipher c){this.s=s;this.cipher=c;}public void close()throws IOException{s.close();}}
 static Client login(InetAddress a,int port,String user)throws Exception{Socket s=new Socket(a,port);s.setSoTimeout(5000);InputStream in=s.getInputStream();OutputStream out=s.getOutputStream();out.write(14);out.write(7);out.flush();byte[] pre=Binary.readExactly(in,9);if((pre[8]&255)!=0)throw new AssertionError("prelogin");long seed=Binary.i64(Binary.readExactly(in,8),0);int[] seeds={0x01020304,0x11223344,(int)(seed>>>32),(int)seed};Method m=DualProfileSocketIntegrationTest.class.getDeclaredMethod("loginPayload",int[].class,String.class);m.setAccessible(true);byte[] payload=(byte[])m.invoke(null,seeds,user);out.write(16);out.write(payload.length);out.write(payload);out.flush();byte[] reply=Binary.readExactly(in,3);if((reply[0]&255)!=2)throw new AssertionError("login rc="+(reply[0]&255));IsaacCipher c=new IsaacCipher(seeds.clone());out.write((185+c.nextInt())&255);out.write(3);out.write(912);out.flush();return new Client(s,c);}
 static void sendCommand(Client c,String cmd)throws Exception{byte[] body=(cmd+"\n").getBytes(StandardCharsets.ISO_8859_1);OutputStream out=c.s.getOutputStream();out.write((103+c.cipher.nextInt())&255);out.write(body.length);out.write(body);out.flush();}
 static void sendWidget(Client c,int w)throws Exception{OutputStream out=c.s.getOutputStream();out.write((185+c.cipher.nextInt())&255);out.write((w>>>8)&255);out.write(w&255);out.flush();}
 static void sendAmount(Client c,int v)throws Exception{OutputStream out=c.s.getOutputStream();out.write((208+c.cipher.nextInt())&255);out.write((v>>>24)&255);out.write((v>>>16)&255);out.write((v>>>8)&255);out.write(v&255);out.flush();}
 static boolean containsByte(byte[]b,int v){for(byte x:b)if((x&255)==v)return true;return false;}
 static byte[] drain(Socket s,long total)throws Exception{InputStream in=s.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();long end=System.currentTimeMillis()+total;while(System.currentTimeMillis()<end){int n=in.available();if(n>0){byte[] b=new byte[Math.min(n,8192)];int r=in.read(b);if(r>0){o.write(b,0,r);end=Math.max(end,System.currentTimeMillis()+50);}}else Thread.sleep(5);}return o.toByteArray();}

 static byte[] drainUntil(Socket s,long timeout,String needle)throws Exception{InputStream in=s.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] n=needle.getBytes(StandardCharsets.ISO_8859_1);long end=System.currentTimeMillis()+timeout;while(System.currentTimeMillis()<end){int av=in.available();if(av>0){byte[] buf=new byte[Math.min(av,8192)];int r=in.read(buf);if(r>0)o.write(buf,0,r);byte[] all=o.toByteArray();if(contains(all,n)){long quiet=System.currentTimeMillis()+80;while(System.currentTimeMillis()<quiet){int more=in.available();if(more>0){byte[] extra=new byte[Math.min(more,8192)];int rr=in.read(extra);if(rr>0){o.write(extra,0,rr);quiet=System.currentTimeMillis()+50;}}else Thread.sleep(5);}return o.toByteArray();}}else Thread.sleep(5);}throw new AssertionError("timeout waiting for "+needle+" bytes="+o.size());}
 static boolean contains(byte[]h,byte[]n){outer:for(int i=0;i+n.length<=h.length;i++){for(int j=0;j<n.length;j++)if(h[i+j]!=n[j])continue outer;return true;}return false;}
 static void has(byte[]b,String x){byte[]n=x.getBytes(StandardCharsets.ISO_8859_1);outer:for(int i=0;i+n.length<=b.length;i++){for(int j=0;j<n.length;j++)if(b[i+j]!=n[j])continue outer;return;}throw new AssertionError("missing "+x+" bytes="+b.length);}
 interface Check{boolean ok();}static void waitFor(Check c,long ms,String label)throws Exception{long e=System.currentTimeMillis()+ms;while(System.currentTimeMillis()<e){if(c.ok())return;Thread.sleep(10);}throw new AssertionError(label+" timeout");}
}
