package spk.local;
import java.io.*;import java.lang.reflect.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import java.util.concurrent.*;
public final class EngineR41TradeApproachSocketTest{
 public static void main(String[]args)throws Exception{
  Path tmp=Files.createTempDirectory("spk-v5141-trade-approach-");String old=System.getProperty("spk.local.accountFile");System.setProperty("spk.local.accountFile",tmp.resolve("opensrc.properties").toString());World world=World.isolatedForTest(80L);InetAddress loop=InetAddress.getByName("127.0.0.1");
  try(ServerSocket ss=new ServerSocket(0,2,loop)){ExecutorService ex=Executors.newFixedThreadPool(3);Future<?> accept=ex.submit(()->{try{for(int i=0;i<2;i++){Socket s=ss.accept();ex.submit(()->new LocalSession(s,true,true,world).run());}}catch(IOException e){throw new RuntimeException(e);}});Client c1=null,c2=null;try{
   c1=login(loop,ss.getLocalPort(),"opensrc");waitFor(()->world.players().size()==1,3000,"primary");drainUntilQuiet(c1.s,1500,100);
   c2=login(loop,ss.getLocalPort(),"opensrc");waitFor(()->world.players().size()==2,3000,"secondary");
   WorldPlayer p1=byName(world,"opensrc"),p2=byName(world,"src");if(p1==null||p2==null)throw new AssertionError("profiles missing");
   waitForReciprocalVisibility(world,p1,p2,4000);drainUntilQuiet(c1.s,2000,100);drainUntilQuiet(c2.s,2000,100);
   int before=Math.abs(p1.movement().x()-p2.movement().x())+Math.abs(p1.movement().y()-p2.movement().y());
   sendPlayerTrade(c1,2);
   byte[] req=waitForRequestAtAdjacency(c2.s,p1,p2,3000,"opensrc:tradereq:\n");
   has(req,"opensrc:tradereq:\n","trade request after approach");
   int after=Math.abs(p1.movement().x()-p2.movement().x())+Math.abs(p1.movement().y()-p2.movement().y());if(after!=1)throw new AssertionError("not adjacent when request observed after="+after);
   sendPlayerTrade(c2,2);
   byte[] o1=awaitPayload(c1.s,3000,80,"primary trade UI","Trading With: src\n");
   byte[] o2=awaitPayload(c2.s,3000,80,"secondary trade UI","Trading With: opensrc\n");
   has(o1,"Trading With: src\n","primary trade UI");has(o2,"Trading With: opensrc\n","secondary trade UI");lacks(o1,"Waiting for other player","initial status p1");lacks(o2,"Waiting for other player","initial status p2");
   System.out.println("V5141_ENGINE_R41_TRADE_APPROACH_SOCKET_PASS beforeManhattan="+before+" afterManhattan="+after+" requestAfterAdjacent=true reciprocalOpen=true initialStatusBlank=true");
  }finally{if(c2!=null)c2.close();if(c1!=null)c1.close();waitFor(()->world.players().size()==0,3000,"logout");accept.get(2,TimeUnit.SECONDS);ex.shutdown();if(!ex.awaitTermination(3,TimeUnit.SECONDS))ex.shutdownNow();}}
  finally{world.close();if(old==null)System.clearProperty("spk.local.accountFile");else System.setProperty("spk.local.accountFile",old);try(java.util.stream.Stream<Path> st=Files.walk(tmp)){st.sorted(Comparator.reverseOrder()).forEach(p->{try{Files.deleteIfExists(p);}catch(Exception ignored){}});}}
 }
 static WorldPlayer byName(World w,String n){for(WorldPlayer p:w.players().snapshot())if(n.equals(p.username()))return p;return null;}
 static final class Client implements AutoCloseable{final Socket s;final IsaacCipher cipher;Client(Socket s,IsaacCipher c){this.s=s;this.cipher=c;}public void close()throws IOException{s.close();}}
 static Client login(InetAddress a,int port,String user)throws Exception{Socket s=new Socket(a,port);s.setSoTimeout(5000);InputStream in=s.getInputStream();OutputStream out=s.getOutputStream();out.write(14);out.write(7);out.flush();byte[] pre=Binary.readExactly(in,9);if((pre[8]&255)!=0)throw new AssertionError("prelogin");long serverSeed=Binary.i64(Binary.readExactly(in,8),0);int[] seeds={0x01020304,0x11223344,(int)(serverSeed>>>32),(int)serverSeed};Method m=DualProfileSocketIntegrationTest.class.getDeclaredMethod("loginPayload",int[].class,String.class);m.setAccessible(true);byte[] payload=(byte[])m.invoke(null,seeds,user);out.write(16);out.write(payload.length);out.write(payload);out.flush();byte[] reply=Binary.readExactly(in,3);if((reply[0]&255)!=2)throw new AssertionError("login rc="+(reply[0]&255));IsaacCipher c=new IsaacCipher(seeds.clone());out.write((185+c.nextInt())&255);out.write(3);out.write(912);out.flush();return new Client(s,c);}
 static void sendPlayerTrade(Client c,int idx)throws Exception{OutputStream out=c.s.getOutputStream();out.write((73+c.cipher.nextInt())&255);out.write(idx&255);out.write((idx>>>8)&255);out.flush();}
 static byte[] drain(Socket s)throws Exception{return drainFor(s,300,70);}static byte[] drainShort(Socket s,long total)throws Exception{return drainFor(s,total,10);}static byte[] drainFor(Socket s,long total,long extend)throws Exception{InputStream in=s.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();long until=System.currentTimeMillis()+total;while(System.currentTimeMillis()<until){int n=in.available();if(n>0){byte[] b=new byte[Math.min(n,8192)];int r=in.read(b);if(r>0){o.write(b,0,r);until=Math.max(until,System.currentTimeMillis()+extend);}}else Thread.sleep(5);}return o.toByteArray();}
 static byte[] drainUntilQuiet(Socket s,long timeout,long quietMillis)throws Exception{InputStream in=s.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();long end=System.currentTimeMillis()+timeout,quietUntil=System.currentTimeMillis()+quietMillis;while(System.currentTimeMillis()<end){int n=in.available();if(n>0){byte[] b=new byte[Math.min(n,8192)];int r=in.read(b);if(r>0){o.write(b,0,r);quietUntil=System.currentTimeMillis()+quietMillis;}}else{if(System.currentTimeMillis()>=quietUntil)return o.toByteArray();Thread.sleep(5);}}return o.toByteArray();}
 static byte[] awaitPayload(Socket s,long timeout,long quietMillis,String label,String...needles)throws Exception{InputStream in=s.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();long end=System.currentTimeMillis()+timeout,quietUntil=Long.MAX_VALUE;boolean matched=false;while(System.currentTimeMillis()<end){int av=in.available();if(av>0){byte[] buf=new byte[Math.min(av,8192)];int r=in.read(buf);if(r>0){o.write(buf,0,r);byte[] all=o.toByteArray();if(hasAll(all,needles)){matched=true;quietUntil=System.currentTimeMillis()+quietMillis;}else if(matched)quietUntil=System.currentTimeMillis()+quietMillis;}}else{if(matched&&System.currentTimeMillis()>=quietUntil)return o.toByteArray();Thread.sleep(5);}}byte[] all=o.toByteArray();throw new AssertionError(label+" timeout bytes="+all.length+" missing="+missing(all,needles));}
 static void waitForReciprocalVisibility(World world,WorldPlayer a,WorldPlayer b,long timeout)throws Exception{long end=System.currentTimeMillis()+timeout;int ai=-1,bi=-1;while(System.currentTimeMillis()<end){Player81WorldSync.Context ca=contextFor(world,a),cb=contextFor(world,b);if(ca!=null&&cb!=null){ai=ca.clientIndexFor(b);bi=cb.clientIndexFor(a);if(ai==2&&bi==2)return;}Thread.sleep(5);}throw new AssertionError("reciprocal Player81 visibility timeout aIndex="+ai+" bIndex="+bi);}
 @SuppressWarnings("unchecked") static Player81WorldSync.Context contextFor(World world,WorldPlayer owner)throws Exception{Field byWorldField=Player81WorldSync.class.getDeclaredField("BY_WORLD");byWorldField.setAccessible(true);synchronized(Player81WorldSync.class){IdentityHashMap<World,?> states=(IdentityHashMap<World,?>)byWorldField.get(null);Object state=states.get(world);if(state==null)return null;Field contextsField=state.getClass().getDeclaredField("contexts");contextsField.setAccessible(true);Map<EntityId,Player81WorldSync.Context> contexts=(Map<EntityId,Player81WorldSync.Context>)contextsField.get(state);return contexts.get(owner.id());}}
 static byte[] waitForRequestAtAdjacency(Socket s,WorldPlayer a,WorldPlayer b,long timeout,String needle)throws Exception{InputStream in=s.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] n=needle.getBytes(StandardCharsets.ISO_8859_1);long end=System.currentTimeMillis()+timeout;while(System.currentTimeMillis()<end){int av=in.available();if(av>0){byte[] buf=new byte[Math.min(av,8192)];int r=in.read(buf);if(r>0)o.write(buf,0,r);byte[] all=o.toByteArray();if(contains(all,n)){int d=Math.abs(a.movement().x()-b.movement().x())+Math.abs(a.movement().y()-b.movement().y());if(d!=1)throw new AssertionError("trade request observed before cardinal adjacency distance="+d);return all;}}else Thread.sleep(5);}throw new AssertionError("trade request timeout bytes="+o.size());}
 static boolean hasAll(byte[] b,String...xs){for(String x:xs)if(!contains(b,x.getBytes(StandardCharsets.ISO_8859_1)))return false;return true;}
 static String missing(byte[] b,String...xs){ArrayList<String> m=new ArrayList<>();for(String x:xs)if(!contains(b,x.getBytes(StandardCharsets.ISO_8859_1)))m.add(x.replace("\n","\\n"));return m.toString();}
 static boolean contains(byte[] b,byte[] n){outer:for(int i=0;i+n.length<=b.length;i++){for(int j=0;j<n.length;j++)if(b[i+j]!=n[j])continue outer;return true;}return false;}
 static void has(byte[] b,String x,String label){byte[] n=x.getBytes(StandardCharsets.ISO_8859_1);if(!contains(b,n))throw new AssertionError(label+" missing bytes="+b.length);}
 static void lacks(byte[] b,String x,String label){byte[] n=x.getBytes(StandardCharsets.ISO_8859_1);if(contains(b,n))throw new AssertionError(label+" unexpectedly present");}
 interface Check{boolean ok();}static void waitFor(Check c,long ms,String label)throws Exception{long e=System.currentTimeMillis()+ms;while(System.currentTimeMillis()<e){if(c.ok())return;Thread.sleep(10);}throw new AssertionError(label+" timeout");}
}
