package spk.local;

import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

/** R8.2 actual Equipment Stats Static Recovery R2, read-only and evidence-preserving. */
final class EquipmentResearchAuthority {
    static final String QUERY_EQUIPSTR="equipstr <itemId> -> C2S103 -> S2C126 key24 -> item id + 14 base stats";
    static final String QUERY_ITEM_LIBRARY="root47500 exact item -> igsearch <exact current item name> via C2S103 -> widgets 47821..47835";
    static final String[] BASE_PROFILE_FIELDS={"stabAtk","slashAtk","crushAtk","magicAtk","rangeAtk","stabDef","slashDef","crushDef","magicDef","rangeDef","strength","rangeStrength","prayer","magicDamage"};
    static final int I_BIN_OVERRIDES=5207,I_BIN_HOVERS=334,NEW_I_BIN_HOVERS=328,EFFECT_TEXT_ROWS=1728,STATIC_MECHANICS_ROWS=729,I_BIN_COMBAT_ROWS=181,EQUIPPABLE_I_BIN_COMBAT_ROWS=99,CORE_BONUS_ROWS=284,SPEED_DAMAGE_ROWS=51,CONDITIONAL_ROWS=565,PET_MODIFIER_ROWS=160;
    static final class Relation{final int itemId;final String itemName,kind,targetText,targetName,targetIds,source,evidence,certainty;Relation(String[]p){itemId=i(p[0]);itemName=u(p[1]);kind=p[2];targetText=u(p[3]);targetName=u(p[4]);targetIds=p[5];source=p[6];evidence=u(p[7]);certainty=p[8];}public String toString(){return "relation="+kind+" target="+targetText+" ids="+(targetIds.isEmpty()?"unresolved":targetIds)+" certainty="+certainty;}}
    static final class Evidence{final int itemId;final String name,source,field,categories,coreTerms,numeric,text;Evidence(String[]p){itemId=i(p[0]);name=u(p[1]);source=p[4];field=p[5];categories=u(p[6]);coreTerms=u(p[7]);numeric=u(p[8]);text=u(p[9]);}public String toString(){return categories+" numeric="+n(numeric)+" text="+text;}}
    private static final LinkedHashMap<Integer,List<Relation>> REL=loadRelations();
    private static final HashMap<Integer,List<Evidence>> EVIDENCE=loadEvidence();
    static int relationshipCount(){int n=0;for(List<Relation>x:REL.values())n+=x.size();return n;}
    static int evidenceRowCount(){int n=0;for(List<Evidence>x:EVIDENCE.values())n+=x.size();return n;}
    static List<Relation> relations(int itemId){List<Relation>x=REL.get(itemId);return x==null?Collections.emptyList():Collections.unmodifiableList(x);}
    static List<Evidence> evidence(int itemId){List<Evidence>x=EVIDENCE.get(itemId);return x==null?Collections.emptyList():Collections.unmodifiableList(x);}
    static String itemSummary(int itemId){ItemAuthorityRepository.Entry e=ItemAuthorityRepository.get(itemId);if(e==null)return "item="+itemId+" UNKNOWN";List<Relation>rs=relations(itemId);List<Evidence>ev=evidence(itemId);String rel=rs.isEmpty()?"none":rs.get(0).toString()+(rs.size()>1?" +"+(rs.size()-1):"");String first=ev.isEmpty()?"none":clip(ev.get(0).toString(),120);return "item="+itemId+" "+ItemAuthorityRepository.stripTags(e.name)+" relation={"+rel+"} staticEvidence="+ev.size()+" first={"+first+"} full14=SERVER_OWNED_IF_UNRECOVERED";}
    static String corpusSummary(){return "relations="+relationshipCount()+" mechanics="+STATIC_MECHANICS_ROWS+" currentIbin="+I_BIN_COMBAT_ROWS+" equippableCurrent="+EQUIPPABLE_I_BIN_COMBAT_ROWS+" core="+CORE_BONUS_ROWS+" speedDamage="+SPEED_DAMAGE_ROWS+" conditional="+CONDITIONAL_ROWS+" petModifiers="+PET_MODIFIER_ROWS;}
    static String boundary(){return "complete14FieldProfiles=0 statically; actual R2 text/deltas/relationships are imported; arbitrary base profiles remain server-owned";}
    private static LinkedHashMap<Integer,List<Relation>>loadRelations(){LinkedHashMap<Integer,List<Relation>>m=new LinkedHashMap<>();try(InputStream in=EquipmentResearchAuthority.class.getResourceAsStream("/spk/local/data/equipment_relationships_r8.tsv")){if(in==null)throw new IllegalStateException("missing equipment relationships");try(BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){br.readLine();String s;while((s=br.readLine())!=null){if(s.isEmpty())continue;String[]p=s.split("\t",-1);if(p.length<9)throw new IllegalStateException("bad relation");Relation r=new Relation(p);m.computeIfAbsent(r.itemId,k->new ArrayList<>()).add(r);}}}catch(IOException e){throw new ExceptionInInitializerError(e);}return m;}
    private static HashMap<Integer,List<Evidence>>loadEvidence(){HashMap<Integer,List<Evidence>>m=new HashMap<>();try(InputStream in=EquipmentResearchAuthority.class.getResourceAsStream("/spk/local/data/research_r82/equipment_static_mechanics_r82.tsv")){if(in==null)throw new IllegalStateException("missing equipment static mechanics R2");try(BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){br.readLine();String s;while((s=br.readLine())!=null){if(s.isEmpty())continue;String[]p=s.split("\t",-1);if(p.length<10)throw new IllegalStateException("bad equipment evidence row fields="+p.length);Evidence e=new Evidence(p);m.computeIfAbsent(e.itemId,k->new ArrayList<>()).add(e);}}}catch(IOException e){throw new ExceptionInInitializerError(e);}return m;}
    private static int i(String s){try{return Integer.parseInt(s);}catch(Exception e){return -1;}}private static String n(String s){return s==null||s.isEmpty()?"none":s;}private static String clip(String s,int n){return s==null?"":(s.length()<=n?s:s.substring(0,n-3)+"...");}private static String u(String s){return s==null?"":s.replace("\\n","\n").replace("\\t","\t").replace("\\\\","\\");}
    private EquipmentResearchAuthority(){}
}
